-- PawPath Breed Insertions (276 breeds)
-- Generated from expanded_breeds.ts + existing breeds
INSERT INTO breeds (species, name) VALUES
  ('canine', 'Affenpinscher'),
  ('canine', 'Afghan Hound'),
  ('canine', 'Airedale Terrier'),
  ('canine', 'Akita'),
  ('canine', 'Alaskan Klee Kai'),
  ('canine', 'Alaskan Malamute'),
  ('canine', 'American English Coonhound'),
  ('canine', 'American Eskimo Dog'),
  ('canine', 'American Hairless Terrier'),
  ('canine', 'American Staffordshire Terrier'),
  ('canine', 'American Water Spaniel'),
  ('canine', 'Anatolian Shepherd Dog'),
  ('canine', 'Australian Cattle Dog'),
  ('canine', 'Australian Kelpie'),
  ('canine', 'Australian Shepherd'),
  ('canine', 'Basenji'),
  ('canine', 'Basset Hound'),
  ('canine', 'Beagle'),
  ('canine', 'Bearded Collie'),
  ('canine', 'Beauceron'),
  ('canine', 'Bedlington Terrier'),
  ('canine', 'Belgian Laekenois'),
  ('canine', 'Belgian Malinois'),
  ('canine', 'Belgian Sheepdog'),
  ('canine', 'Belgian Tervuren'),
  ('canine', 'Bergamasco Sheepdog'),
  ('canine', 'Berger Picard'),
  ('canine', 'Bernese Mountain Dog'),
  ('canine', 'Bichon Frise'),
  ('canine', 'Black Russian Terrier'),
  ('canine', 'Black and Tan Coonhound'),
  ('canine', 'Bloodhound'),
  ('canine', 'Bluetick Coonhound'),
  ('canine', 'Boerboel'),
  ('canine', 'Border Collie'),
  ('canine', 'Border Terrier'),
  ('canine', 'Borzoi'),
  ('canine', 'Boston Terrier'),
  ('canine', 'Boykin Spaniel'),
  ('canine', 'Briard'),
  ('canine', 'Brittany'),
  ('canine', 'Brussels Griffon'),
  ('canine', 'Bulldog'),
  ('canine', 'Bullmastiff'),
  ('canine', 'Cairn Terrier'),
  ('canine', 'Cane Corso'),
  ('canine', 'Cardigan Welsh Corgi'),
  ('canine', 'Caucasian Shepherd Dog'),
  ('canine', 'Cavalier King Charles Spaniel'),
  ('canine', 'Central Asian Shepherd Dog'),
  ('canine', 'Cesky Terrier'),
  ('canine', 'Chesapeake Bay Retriever'),
  ('canine', 'Chihuahua'),
  ('canine', 'Chinese Crested'),
  ('canine', 'Chinese Shar-Pei'),
  ('canine', 'Chinook'),
  ('canine', 'Chow Chow'),
  ('canine', 'Cirneco dell''Etna'),
  ('canine', 'Cocker Spaniel'),
  ('canine', 'Collie'),
  ('canine', 'Coton de Tulear'),
  ('canine', 'Curly-Coated Retriever'),
  ('canine', 'Czechoslovakian Wolfdog'),
  ('canine', 'Dachshund'),
  ('canine', 'Dalmatian'),
  ('canine', 'Dandie Dinmont Terrier'),
  ('canine', 'Dog Argentino'),
  ('canine', 'Dogo Argentino'),
  ('canine', 'Dogue de Bordeaux'),
  ('canine', 'English Setter'),
  ('canine', 'English Springer Spaniel'),
  ('canine', 'English Toy Spaniel'),
  ('canine', 'Entlebucher Mountain Dog'),
  ('canine', 'Field Spaniel'),
  ('canine', 'Finnish Lapphund'),
  ('canine', 'Finnish Spitz'),
  ('canine', 'Flat-Coated Retriever'),
  ('canine', 'French Bulldog'),
  ('canine', 'German Shorthaired Pointer'),
  ('canine', 'German Wirehaired Pointer'),
  ('canine', 'Giant Schnauzer'),
  ('canine', 'Glen of Imaal Terrier'),
  ('canine', 'Gordon Setter'),
  ('canine', 'Great Pyrenees'),
  ('canine', 'Greater Swiss Mountain Dog'),
  ('canine', 'Greyhound'),
  ('canine', 'Hamiltonstovare'),
  ('canine', 'Harrier'),
  ('canine', 'Havanese'),
  ('canine', 'Hovawart'),
  ('canine', 'Ibizan Hound'),
  ('canine', 'Icelandic Sheepdog'),
  ('canine', 'Irish Red and White Setter'),
  ('canine', 'Irish Setter'),
  ('canine', 'Irish Terrier'),
  ('canine', 'Irish Wolfhound'),
  ('canine', 'Italian Greyhound'),
  ('canine', 'Japanese Chin'),
  ('canine', 'Keeshond'),
  ('canine', 'Kerry Blue Terrier'),
  ('canine', 'Komondor'),
  ('canine', 'Kuvasz'),
  ('canine', 'Lagotto Romagnolo'),
  ('canine', 'Lakeland Terrier'),
  ('canine', 'Lancashire Heeler'),
  ('canine', 'Landseer'),
  ('canine', 'Leonberger'),
  ('canine', 'Lhasa Apso'),
  ('canine', 'Lowchen'),
  ('canine', 'Maltese'),
  ('canine', 'Manchester Terrier'),
  ('canine', 'Mastiff'),
  ('canine', 'Miniature American Shepherd'),
  ('canine', 'Miniature Bull Terrier'),
  ('canine', 'Miniature Pinscher'),
  ('canine', 'Miniature Schnauzer'),
  ('canine', 'Neapolitan Mastiff'),
  ('canine', 'Newfoundland'),
  ('canine', 'Norfolk Terrier'),
  ('canine', 'Norwegian Buhund'),
  ('canine', 'Norwegian Elkhound'),
  ('canine', 'Norwegian Lundehund'),
  ('canine', 'Norwich Terrier'),
  ('canine', 'Nova Scotia Duck Tolling Retriever'),
  ('canine', 'Old English Sheepdog'),
  ('canine', 'Otterhound'),
  ('canine', 'Papillon'),
  ('canine', 'Parson Russell Terrier'),
  ('canine', 'Pekingese'),
  ('canine', 'Pembroke Welsh Corgi'),
  ('canine', 'Peruvian Inca Orchid'),
  ('canine', 'Petit Basset Griffon Vendeen'),
  ('canine', 'Pharaoh Hound'),
  ('canine', 'Plott Hound'),
  ('canine', 'Pointer'),
  ('canine', 'Polish Lowland Sheepdog'),
  ('canine', 'Pomeranian'),
  ('canine', 'Poodle (Miniature)'),
  ('canine', 'Poodle (Toy)'),
  ('canine', 'Portuguese Podengo Pequeno'),
  ('canine', 'Portuguese Sheepdog'),
  ('canine', 'Portuguese Water Dog'),
  ('canine', 'Pug'),
  ('canine', 'Puli'),
  ('canine', 'Pyrenean Shepherd'),
  ('canine', 'Rat Terrier'),
  ('canine', 'Ratonero Bodeguero Andaluz'),
  ('canine', 'Redbone Coonhound'),
  ('canine', 'Rhodesian Ridgeback'),
  ('canine', 'Russell Terrier'),
  ('canine', 'Saint Bernard'),
  ('canine', 'Saluki'),
  ('canine', 'Samoyed'),
  ('canine', 'Schipperke'),
  ('canine', 'Scottish Deerhound'),
  ('canine', 'Scottish Terrier'),
  ('canine', 'Sealyham Terrier'),
  ('canine', 'Segugio Italiano'),
  ('canine', 'Shetland Sheepdog'),
  ('canine', 'Shiba Inu'),
  ('canine', 'Shih Tzu'),
  ('canine', 'Siberian Husky'),
  ('canine', 'Silky Terrier'),
  ('canine', 'Skye Terrier'),
  ('canine', 'Sloughi'),
  ('canine', 'Small Munsterlander'),
  ('canine', 'Smooth Fox Terrier'),
  ('canine', 'Spanish Water Dog'),
  ('canine', 'Spinone Italiano'),
  ('canine', 'Staffordshire Bull Terrier'),
  ('canine', 'Standard Schnauzer'),
  ('canine', 'Sussex Spaniel'),
  ('canine', 'Swedish Vallhund'),
  ('canine', 'Thai Ridgeback'),
  ('canine', 'Tibetan Mastiff'),
  ('canine', 'Tibetan Spaniel'),
  ('canine', 'Tibetan Terrier'),
  ('canine', 'Toy Fox Terrier'),
  ('canine', 'Transylvanian Hound'),
  ('canine', 'Treeing Tennessee Brindle'),
  ('canine', 'Treeing Walker Coonhound'),
  ('canine', 'Vizsla'),
  ('canine', 'Weimaraner'),
  ('canine', 'Welsh Springer Spaniel'),
  ('canine', 'Welsh Terrier'),
  ('canine', 'West Highland White Terrier'),
  ('canine', 'Whippet'),
  ('canine', 'Wire Fox Terrier'),
  ('canine', 'Wirehaired Pointing Griffon'),
  ('canine', 'Wirehaired Vizsla'),
  ('canine', 'Xoloitzcuintli'),
  ('canine', 'Yorkshire Terrier'),
  ('feline', 'American Curl'),
  ('feline', 'American Shorthair'),
  ('feline', 'American Wirehair'),
  ('feline', 'Australian Mist'),
  ('feline', 'Balinese'),
  ('feline', 'Bombay'),
  ('feline', 'Brazilian Shorthair'),
  ('feline', 'Burmilla'),
  ('feline', 'Celtic Shorthair'),
  ('feline', 'Chantilly-Tiffany'),
  ('feline', 'Chartreux'),
  ('feline', 'Chausie'),
  ('feline', 'Colorpoint Shorthair'),
  ('feline', 'Cymric'),
  ('feline', 'Domestic Longhair'),
  ('feline', 'Domestic Medium Hair'),
  ('feline', 'Domestic Shorthair'),
  ('feline', 'Dragon Li'),
  ('feline', 'Egyptian Mau'),
  ('feline', 'European Burmese'),
  ('feline', 'Exotic Shorthair'),
  ('feline', 'Foldex'),
  ('feline', 'German Rex'),
  ('feline', 'Havana Brown'),
  ('feline', 'Himalayan'),
  ('feline', 'Japanese Bobtail'),
  ('feline', 'Khao Manee'),
  ('feline', 'Kinkalow'),
  ('feline', 'Korat'),
  ('feline', 'Kurilian Bobtail'),
  ('feline', 'LaPerm'),
  ('feline', 'Lamkin'),
  ('feline', 'Lykoi'),
  ('feline', 'Manx'),
  ('feline', 'Mekong Bobtail'),
  ('feline', 'Munchkin'),
  ('feline', 'Nebelung'),
  ('feline', 'Ocicat'),
  ('feline', 'Ojos Azules'),
  ('feline', 'Peterbald'),
  ('feline', 'Pixiebob'),
  ('feline', 'RagaMuffin'),
  ('feline', 'Selkirk Rex'),
  ('feline', 'Serengeti'),
  ('feline', 'Siberian'),
  ('feline', 'Singapura'),
  ('feline', 'Skookum'),
  ('feline', 'Snowshoe'),
  ('feline', 'Sokoke'),
  ('feline', 'Sokoto'),
  ('feline', 'Somali'),
  ('feline', 'Thai'),
  ('feline', 'Toyger'),
  ('feline', 'Turkish Angora'),
  ('feline', 'Turkish Van'),
  ('feline', 'Ural Rex'),
  ('feline', 'Welsh Cat'),
  ('feline', 'York Chocolate'),
  ('canine', 'Labrador Retriever'),
  ('canine', 'Golden Retriever'),
  ('canine', 'German Shepherd'),
  ('canine', 'Poodle (Standard)'),
  ('canine', 'Rottweiler'),
  ('canine', 'Boxer'),
  ('canine', 'Great Dane'),
  ('canine', 'Doberman Pinscher'),
  ('canine', 'Bull Terrier'),
  ('feline', 'Persian'),
  ('feline', 'Maine Coon'),
  ('feline', 'Siamese'),
  ('feline', 'Bengal'),
  ('feline', 'Sphynx'),
  ('feline', 'Ragdoll'),
  ('feline', 'Scottish Fold'),
  ('feline', 'Abyssinian'),
  ('feline', 'Burmese'),
  ('feline', 'Norwegian Forest Cat'),
  ('feline', 'British Shorthair'),
  ('feline', 'Devon Rex'),
  ('feline', 'Cornish Rex'),
  ('feline', 'Russian Blue'),
  ('feline', 'Oriental Shorthair'),
  ('feline', 'Tonkinese'),
  ('feline', 'Birman');
